### ISSUE TITLE
Would like different sized images and the ability to individually position pics

### ISSUE THREAD

**Issue by jsnkuhn** [gameboy9/randoTracker#10]
Right now the pic tag restricts us to grids with uniform size icons as determined by Gap and size attr in the parent pictures TAG. 

Example of what I want to do with spells for dwr that I can't do right now:
https://codepen.io/jsnkuhn/pen/VMJPMZ

Also example of a layout for link's awakening icons that is possible right now but tedious (need to fill "empty" grid spots with transparent images). Positioning icons individually would be easier :

https://www.zeldadungeon.net/Zelda04/Walkthrough/09/026.png

**Comment by Datyedyeguy** [comment]
Thoughts on this is we have a layout attribute on the pictures tag.  Depending on what it is (defaults to grid, freeform also an option) it builds out the UI differently.  xGap and such wouldn't make sense in a freeform UI, then it's probably just X/Y/size positioning.

**Comment by jsnkuhn** [comment]
Yeah that sounds like the way to go. I'm assuming that in freeform mode the x and y coordinates of the individual `<picture>` tags would be relative to the top left corner of the parent '<pictures>' tag?

**Comment by Datyedyeguy** [comment]
Yup, that can be done.
