### ISSUE TITLE
Change .xml icon appearance in the open dialog?

### ISSUE THREAD

**Issue by jsnkuhn** [gameboy9/randoTracker#21]
In an attempt to make the process of opening an xml a bit more user friendly. Would it be possible to change the default xml icon to a game cartridge icon? Either generic or game specific? To evoke the idea of plugging a cartridge (the xml) into a console (RandoTracker)

**Comment by Datyedyeguy** [comment]
As I understand it, those icons are actually powered by Windows and are done based on the file extension/default application setup to open XML files.  Not much we can do here.

**Comment by jsnkuhn** [comment]
:disappointed: okie doike. That's what I thought but was hoping to be pleasantly surprised.
