### ISSUE TITLE
swapping out icon sets for marathon layout

### ISSUE THREAD

**Issue by jsnkuhn** [gameboy9/randoTracker#32]
From randoMania #marathon: 

capt_uhu - Today at 10:28 AM
hey @Datyedyeguy could there be a way to swap out the icon sets in the same way we are doing backgrounds right now? That would make it so we can use the same xml for lets say all the 2 player races.

Datyedyeguy - Today at 10:29 AM
I can see what I can do...
Perhaps a tag describing all the image root paths so you can pick one. Then reload images as you go. I can try and work on that tonight...
Put in a github thing so I don't forget. ;)

**Comment by Datyedyeguy** [comment]
We are thinking of just image file swaps, right? Same number/position of picture elements, etc?

**Comment by jsnkuhn** [comment]
hmm... hadn't thought of that. So an example for 4 player would be the current super mario land 2, zelda 2 and final fantasy. So i guess number of icons and icon sizes etc. differs on all of those.

So i guess what we are looking for is to create one xml file that has multiple <pictures> tags with differing attributes and have a drop down to chose between the different <pictures> tags?

**Comment by Datyedyeguy** [comment]
So what's the end goal? Having a drop down to select a layout? We can look at all the Xml files in the root directory and add them to a drop down. Will save folks from having to use the open file dialog then...

**Comment by jsnkuhn** [comment]
the drop down would need to select the `pictures` content and swap it out on top of the marathon background. 

So my understanding is that there will be 3 different marathon specific backgrounds:
- A one player marathon background 
- a two player marathon background
- a four player marathon background

The position of the `pictures` content and the space available for the icons would always be the same on the 2 player marathon background. So, just pulling from the existing, lets say, zelda 2 xml file wont necessarily work. We need to be sure the icon are sized properly for the marathon background.

**Comment by Datyedyeguy** [comment]
I think I understand now. 3 marathon layouts for different player counts, but multiple image sets and such within each one for the different games. Hmm, ideas are flowing... Think I can work with that.

**Comment by jsnkuhn** [comment]
will also need swapping out neutralpics for marathon layout. Game specific neutralpics and icons should be swaped with one drop down

**Comment by Datyedyeguy** [comment]
This should now be done for 4.4.2
